version: '3'
services:
  prophet:
    image: honir/prophet:latest
    ports:
      - "8888:8888"
    volumes:
      - ./src:/usr/src
    command: jupyter notebook --no-browser --ip 0.0.0.0 --allow-root --NotebookApp.token=

  explore:
    build:
      context: ./docker/explore
      dockerfile: explore.dockerfile
    ports:
      - "8888:8888"
    volumes:
      - ./src:/usr/src
    command: jupyter notebook --no-browser --ip 0.0.0.0 --allow-root --NotebookApp.token=